name: XRay
channels:
  - anaconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - nltk
  - scikit-learn  
  - efficientnet
  - tensorflow
  - imblearn
  - matplotlib
  - re
  - json
  - os
  - pip

